services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto/conf.d/mosquitto.conf:/mosquitto/conf.d/mosquitto.conf
      - ./mosquitto/mosquitto.conf:/mosquitto/mosquitto.conf
      - ./mosquitto/pwd:/mosquitto.passwd
      - ./mosquitto/acl:/mosquitto/acl
    networks:
      - mqtt-net

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mqtt-net

networks:
  mqtt-net:

volumes:
  caddy_data:
  caddy_config:

# version: "3.9"

# services:
#   mosquitto:
#     image: eclipse-mosquitto:2
#     container_name: mosquitto
#     volumes:
#       - ./mosquitto:/mosquitto/config
#     networks:
#       - internal

#   caddy:
#     image: caddy:2
#     container_name: caddy
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./caddy/Caddyfile:/etc/caddy/Caddyfile
#       - caddy_data:/data
#       - caddy_config:/config
#     depends_on:
#       - mosquitto
#     networks:
#       - internal

# networks:
#   internal:

# volumes:
#   caddy_data:
#   caddy_config:

